### ISSUE TITLE
Insufficient research coverage

### ISSUE THREAD

**Issue by gitcnd** [AusDTO/service-handbook#16]
There is no obvious assessment of current technologies in this guide.
There is a whole lot of "legacy" research, covering what "users" did in the past.
Where is the forward-looking research?  What about finding out how to move things forward, instead of replicate what's already done?  

There needs to be a vendor-identification stage followed by an investigation into modern products and technologies that compete in those industries, or else your research is doomed to be stale before it's even complete!

**Comment by colugo** [comment]
Hi gitcnd, thanks for taking the time to read our handbook and provide feedback. 
So I can properly address your suggestions, could you please give me a little more detail about which area of the handbook you're specifically addressing? 

Have you read the sections of future vision @ http://ausdto.github.io/service-handbook/alpha/1-introduction/1-2-future-vision.html and technology @ http://ausdto.github.io/service-handbook/alpha/3-building-prototypes/3-2-tools-technology.html as they talk about some of what I'm interpreting you're  suggesting?
